apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ingress-practice
  name: ingress-practice
  # namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-practice
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ingress-practice
    spec:
      containers:
      - image: si3mshady/time
        name: time
        ports:
          - containerPort: 3000