
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elliott-ingress-svc
  namespace: elliott-ingress
spec:
  rules:
    - host: "*.amazonaws.com"
      http:
       paths:
        - path: /
          pathType: Prefix
          backend:
            service: 
              name: elliott-ingress-svc
              port:
                number: 3000

    - host: "ingress.elliottlamararnold.com"
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service: 
              name: elliott-ingress-svc
              port:
                number: 3000